###
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Nino",
    "email": "nino@gmail.com",
    "password": "123456" 
}

###
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "fotolinda",
    "description": "Descição",
    "type": "normal",
    "authorId": "eb3bc97a-8577-4da8-a834-1a9beb576e43"

}

###
GET http://localhost:3003/post/c652d97c-19f4-4602-9fb0-1d2522d25251

###
GET http://localhost:3003/user/friend/4db7ba54-5209-4edb-85ba-0de5c4a30523