
// endpoints User
###
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "name": "Nino",
    "email": "nino@gmail.com",
    "password": "123456" 
}


// endpoints Posts
###
//criar post
POST http://localhost:3003/post/create
Content-Type: application/json

{
    "photo": "fotolinda",
    "description": "Descição",
    "type": "normal",
    "authorId": "eb3bc97a-8577-4da8-a834-1a9beb576e43"

}

###
// pegar post
GET http://localhost:3003/post/c652d97c-19f4-4602-9fb0-1d2522d25251


// endpoints friends

###
// get friends
GET http://localhost:3003/friends/4db7ba54-5209-4edb-85ba-0de5c4a30523

###
// fazer amizade
POST http://localhost:3003/friends/create
Content-Type: application/json

{
    "idFriend1": "d1a3c249-847f-4b3e-9ab1-e0b43a1b5349",
    "idFriend2": "eb3bc97a-8577-4da8-a834-1a9beb576e43"
}

###
// desfazer amizade
DELETE  http://localhost:3003/friends/delete
Content-Type: application/json

{
    "idFriend1": "d1a3c249-847f-4b3e-9ab1-e0b43a1b5349",
    "idFriend2": "eb3bc97a-8577-4da8-a834-1a9beb576e43"
}